language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - npm i pm2 -g
  - pm2 start core/main.js --name server
  - pm2 list
script:
  - npm run test
after_script:
  - pm2 stop server