language: node_js
os: windows
node_js: 
  - "node"
cache:
  directories:
    - "node_modules"
before_script:
  - node ./dev/src/setup-ci.js
  - node ./core/main.js &
  - sleep 15
script:
  - npm run test